### ISSUE TITLE
yitaoSu: inaccessible or not found

### ISSUE THREAD

**Issue by chenhucxc** [AndriiChemer/XapkInstaller#1]
What is os.writeBytes("yitaoSu\n")？

**Comment by AndriiChemer** [comment]
@chenhucxc can you show me place there is this part of code?

**Comment by chenhucxc** [comment]
Thanks
com.inkbook.installer.storytel.core.utils.ShellExecutor.kt
···kotlin
fun execute(installCommand: String): Boolean {
        var os: DataOutputStream? = null
        try {
            val process = Runtime.getRuntime().exec("su")
            os = DataOutputStream(process.outputStream)
            os.writeBytes("yitaoSu\n")
            os.writeBytes("exec\n")
            os.writeBytes(installCommand)
            os.writeBytes("exit\n")
            os.flush()

            val result = process.waitFor()

            return result == 0
        } catch (e: Exception) {
            e.printStackTrace()
            return false
        } finally {
            os?.close()
        }
    }
```

**Comment by AndriiChemer** [comment]
@chenhucxc My current company has own devices with custom Android and it is need for execution. I think you don’t need it for normal Android devices. (But I didn’t check it)

**Comment by chenhucxc** [comment]
I got it，thanks
